resources:  {
  resource_id:  "example_vn_azure"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VirtualNetworkArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  AZURE
        }
        name:  "example_vn"
        cidr_block:  "10.0.0.0/16"
      }
    }
  }
}
resources:  {
  resource_id:  "example_vn_aws"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VirtualNetworkArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  AWS
        }
        name:  "example_vn"
        cidr_block:  "10.0.0.0/16"
      }
    }
  }
}
resources:  {
  resource_id:  "subnet_aws"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.SubnetArgs]:  {
        name:  "subnet"
        cidr_block:  "10.0.2.0/24"
        virtual_network_id:  "example_vn_aws"
        availability_zone:  2
      }
    }
  }
}
resources:  {
  resource_id:  "subnet_azure"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.SubnetArgs]:  {
        name:  "subnet"
        cidr_block:  "10.0.2.0/24"
        virtual_network_id:  "example_vn_azure"
        availability_zone:  2
      }
    }
  }
}
resources:  {
  resource_id:  "rt_azure"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.RouteTableArgs]:  {
        name:  "test-rt"
        virtual_network_id:  "example_vn_azure"
        routes:  {
          cidr_block:  "0.0.0.0/0"
          destination:  INTERNET
        }
      }
    }
  }
}
resources:  {
  resource_id:  "rt_aws"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.RouteTableArgs]:  {
        name:  "test-rt"
        virtual_network_id:  "example_vn_aws"
        routes:  {
          cidr_block:  "0.0.0.0/0"
          destination:  INTERNET
        }
      }
    }
  }
}
resources:  {
  resource_id:  "rta_aws"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.RouteTableAssociationArgs]:  {
        subnet_id:  "subnet_aws"
        route_table_id:  "rt_aws"
      }
    }
  }
}
resources:  {
  resource_id:  "rta_azure"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.RouteTableAssociationArgs]:  {
        subnet_id:  "subnet_azure"
        route_table_id:  "rt_azure"
      }
    }
  }
}
resources:  {
  resource_id:  "vm_aws"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VirtualMachineArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  AWS
        }
        name:  "test-vm"
        vm_size:  GENERAL_NANO
        user_data_base64:  "ZWNobyAnSGVsbG8gV29ybGQn"
        subnet_id:  "subnet_aws"
        public_ssh_key:  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwSjgjEIKewBWACaOVGg4qsGSHhIeteCmbtn4/DpL0yugLf5c/K/RJVQOKG+dVXVfWD3oAb4JY8jvkZdVACcuocoCewrIEHXxZJmGehxgCeUG8HZ+14mODosUOUYCe3kKCWU2SnUhjX+8x6btxqDOEhtghN3qR52kjm/OUw0Ap43weR1sdkJwtUz7CAXzdCxEKj16R0SY/dNn3uIISPetqm7vqy0ecMJdasbj/X6IAKeiZHe5UKtmOCGYMLwYfKqsrEnzk5rCfa3PK0iYoPv8AB3ocpONcuBshJyDZWhaFBhBrs5SGrWcF34wckD37SNtRZJt+Fuaxe8MpqUVueGTgFViKokCxCfbTnKWRbdGXpSfS6Q0OSvZTWkUEy5ZjxsA03LT4Bcbzq19sABdbyrcEMdv8bq0fhNyGJcGYNJr2uC4+J7irXAM/TuFje4CpJ0G+J3gCrQ2BUeWOYBdjfeP+LckgVXP+TMcEEe4iq5B9psyIS7o58KeNQdFH9jQteIE= joao@Joaos-MBP"
        generate_public_ip:  true
      }
    }
  }
}
resources:  {
  resource_id:  "vm_azure"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VirtualMachineArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  AZURE
        }
        name:  "test-vm"
        vm_size:  GENERAL_NANO
        user_data_base64:  "ZWNobyAnSGVsbG8gV29ybGQn"
        subnet_id:  "subnet_azure"
        public_ssh_key:  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwSjgjEIKewBWACaOVGg4qsGSHhIeteCmbtn4/DpL0yugLf5c/K/RJVQOKG+dVXVfWD3oAb4JY8jvkZdVACcuocoCewrIEHXxZJmGehxgCeUG8HZ+14mODosUOUYCe3kKCWU2SnUhjX+8x6btxqDOEhtghN3qR52kjm/OUw0Ap43weR1sdkJwtUz7CAXzdCxEKj16R0SY/dNn3uIISPetqm7vqy0ecMJdasbj/X6IAKeiZHe5UKtmOCGYMLwYfKqsrEnzk5rCfa3PK0iYoPv8AB3ocpONcuBshJyDZWhaFBhBrs5SGrWcF34wckD37SNtRZJt+Fuaxe8MpqUVueGTgFViKokCxCfbTnKWRbdGXpSfS6Q0OSvZTWkUEy5ZjxsA03LT4Bcbzq19sABdbyrcEMdv8bq0fhNyGJcGYNJr2uC4+J7irXAM/TuFje4CpJ0G+J3gCrQ2BUeWOYBdjfeP+LckgVXP+TMcEEe4iq5B9psyIS7o58KeNQdFH9jQteIE= joao@Joaos-MBP"
        generate_public_ip:  true
      }
    }
  }
}
resources:  {
  resource_id:  "rg1"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.ResourceGroupArgs]:  {
        common_parameters:  {
          location:  EU_WEST_1
          cloud_provider:  AZURE
        }
        name:  "rg1"
      }
    }
  }
}


# proto-file: api/proto/configpb/config.proto
# proto-import: api/proto/resourcespb/database.proto
# proto-import: api/proto/resourcespb/kubernetes_cluster.proto
# proto-import: api/proto/resourcespb/kubernetes_node_pool.proto
# proto-import: api/proto/resourcespb/lambda.proto
# proto-import: api/proto/resourcespb/network_interface.proto
# proto-import: api/proto/resourcespb/network_security_group.proto
# proto-import: api/proto/resourcespb/public_ip.proto
# proto-import: api/proto/resourcespb/resource_group.proto
# proto-import: api/proto/resourcespb/route_table_association.proto
# proto-import: api/proto/resourcespb/object_storage.proto
# proto-import: api/proto/resourcespb/object_storage_object.proto
# proto-import: api/proto/resourcespb/route_table.proto
# proto-import: api/proto/resourcespb/subnet.proto
# proto-import: api/proto/resourcespb/vault.proto
# proto-import: api/proto/resourcespb/vault_access_policy.proto
# proto-import: api/proto/resourcespb/vault_secret.proto
# proto-import: api/proto/resourcespb/virtual_machine.proto
# proto-import: api/proto/resourcespb/virtual_network.proto
# proto-message: config.Config
