// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/proto/resourcespb/network_security_group.proto

package resourcespb

import (
	commonpb "github.com/multycloud/multy/api/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_BOTH_DIRECTIONS Direction = 0
	Direction_INGRESS         Direction = 1
	Direction_EGRESS          Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "BOTH_DIRECTIONS",
		1: "INGRESS",
		2: "EGRESS",
	}
	Direction_value = map[string]int32{
		"BOTH_DIRECTIONS": 0,
		"INGRESS":         1,
		"EGRESS":          2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_resourcespb_network_security_group_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_api_proto_resourcespb_network_security_group_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{0}
}

type CreateNetworkSecurityGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *NetworkSecurityGroupArgs `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CreateNetworkSecurityGroupRequest) Reset() {
	*x = CreateNetworkSecurityGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNetworkSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkSecurityGroupRequest) ProtoMessage() {}

func (x *CreateNetworkSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNetworkSecurityGroupRequest) GetResource() *NetworkSecurityGroupArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReadNetworkSecurityGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *ReadNetworkSecurityGroupRequest) Reset() {
	*x = ReadNetworkSecurityGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNetworkSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNetworkSecurityGroupRequest) ProtoMessage() {}

func (x *ReadNetworkSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNetworkSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*ReadNetworkSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{1}
}

func (x *ReadNetworkSecurityGroupRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type UpdateNetworkSecurityGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string                    `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Resource   *NetworkSecurityGroupArgs `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *UpdateNetworkSecurityGroupRequest) Reset() {
	*x = UpdateNetworkSecurityGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNetworkSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkSecurityGroupRequest) ProtoMessage() {}

func (x *UpdateNetworkSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateNetworkSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNetworkSecurityGroupRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateNetworkSecurityGroupRequest) GetResource() *NetworkSecurityGroupArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteNetworkSecurityGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *DeleteNetworkSecurityGroupRequest) Reset() {
	*x = DeleteNetworkSecurityGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNetworkSecurityGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkSecurityGroupRequest) ProtoMessage() {}

func (x *DeleteNetworkSecurityGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkSecurityGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkSecurityGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNetworkSecurityGroupRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type PortRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{4}
}

func (x *PortRange) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *PortRange) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

type NetworkSecurityRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol  string     `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Priority  int64      `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	PortRange *PortRange `protobuf:"bytes,3,opt,name=port_range,json=portRange,proto3" json:"port_range,omitempty"`
	CidrBlock string     `protobuf:"bytes,4,opt,name=cidr_block,json=cidrBlock,proto3" json:"cidr_block,omitempty"`
	Direction Direction  `protobuf:"varint,5,opt,name=direction,proto3,enum=dev.multy.resources.Direction" json:"direction,omitempty"`
}

func (x *NetworkSecurityRule) Reset() {
	*x = NetworkSecurityRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityRule) ProtoMessage() {}

func (x *NetworkSecurityRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityRule.ProtoReflect.Descriptor instead.
func (*NetworkSecurityRule) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkSecurityRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkSecurityRule) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *NetworkSecurityRule) GetPortRange() *PortRange {
	if x != nil {
		return x.PortRange
	}
	return nil
}

func (x *NetworkSecurityRule) GetCidrBlock() string {
	if x != nil {
		return x.CidrBlock
	}
	return ""
}

func (x *NetworkSecurityRule) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_BOTH_DIRECTIONS
}

type NetworkSecurityGroupGcpOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *NetworkSecurityGroupGcpOverride) Reset() {
	*x = NetworkSecurityGroupGcpOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityGroupGcpOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityGroupGcpOverride) ProtoMessage() {}

func (x *NetworkSecurityGroupGcpOverride) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityGroupGcpOverride.ProtoReflect.Descriptor instead.
func (*NetworkSecurityGroupGcpOverride) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkSecurityGroupGcpOverride) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type NetworkSecurityGroupArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.ResourceCommonArgs     `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VirtualNetworkId string                           `protobuf:"bytes,3,opt,name=virtual_network_id,json=virtualNetworkId,proto3" json:"virtual_network_id,omitempty"`
	Rules            []*NetworkSecurityRule           `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	GcpOverride      *NetworkSecurityGroupGcpOverride `protobuf:"bytes,5,opt,name=gcp_override,json=gcpOverride,proto3" json:"gcp_override,omitempty"`
}

func (x *NetworkSecurityGroupArgs) Reset() {
	*x = NetworkSecurityGroupArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityGroupArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityGroupArgs) ProtoMessage() {}

func (x *NetworkSecurityGroupArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityGroupArgs.ProtoReflect.Descriptor instead.
func (*NetworkSecurityGroupArgs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkSecurityGroupArgs) GetCommonParameters() *commonpb.ResourceCommonArgs {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *NetworkSecurityGroupArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkSecurityGroupArgs) GetVirtualNetworkId() string {
	if x != nil {
		return x.VirtualNetworkId
	}
	return ""
}

func (x *NetworkSecurityGroupArgs) GetRules() []*NetworkSecurityRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkSecurityGroupArgs) GetGcpOverride() *NetworkSecurityGroupGcpOverride {
	if x != nil {
		return x.GcpOverride
	}
	return nil
}

type NetworkSecurityGroupAwsOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecurityGroupId string `protobuf:"bytes,1,opt,name=security_group_id,json=securityGroupId,proto3" json:"security_group_id,omitempty"`
}

func (x *NetworkSecurityGroupAwsOutputs) Reset() {
	*x = NetworkSecurityGroupAwsOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityGroupAwsOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityGroupAwsOutputs) ProtoMessage() {}

func (x *NetworkSecurityGroupAwsOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityGroupAwsOutputs.ProtoReflect.Descriptor instead.
func (*NetworkSecurityGroupAwsOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkSecurityGroupAwsOutputs) GetSecurityGroupId() string {
	if x != nil {
		return x.SecurityGroupId
	}
	return ""
}

type NetworkSecurityGroupAzureOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkSecurityGroupId string `protobuf:"bytes,1,opt,name=network_security_group_id,json=networkSecurityGroupId,proto3" json:"network_security_group_id,omitempty"`
}

func (x *NetworkSecurityGroupAzureOutputs) Reset() {
	*x = NetworkSecurityGroupAzureOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityGroupAzureOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityGroupAzureOutputs) ProtoMessage() {}

func (x *NetworkSecurityGroupAzureOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityGroupAzureOutputs.ProtoReflect.Descriptor instead.
func (*NetworkSecurityGroupAzureOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkSecurityGroupAzureOutputs) GetNetworkSecurityGroupId() string {
	if x != nil {
		return x.NetworkSecurityGroupId
	}
	return ""
}

type NetworkSecurityGroupGcpOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComputeFirewallId []string `protobuf:"bytes,1,rep,name=compute_firewall_id,json=computeFirewallId,proto3" json:"compute_firewall_id,omitempty"`
}

func (x *NetworkSecurityGroupGcpOutputs) Reset() {
	*x = NetworkSecurityGroupGcpOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityGroupGcpOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityGroupGcpOutputs) ProtoMessage() {}

func (x *NetworkSecurityGroupGcpOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityGroupGcpOutputs.ProtoReflect.Descriptor instead.
func (*NetworkSecurityGroupGcpOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkSecurityGroupGcpOutputs) GetComputeFirewallId() []string {
	if x != nil {
		return x.ComputeFirewallId
	}
	return nil
}

type NetworkSecurityGroupResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.CommonResourceParameters `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VirtualNetworkId string                             `protobuf:"bytes,3,opt,name=virtual_network_id,json=virtualNetworkId,proto3" json:"virtual_network_id,omitempty"`
	Rules            []*NetworkSecurityRule             `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	GcpOverride      *NetworkSecurityGroupGcpOverride   `protobuf:"bytes,5,opt,name=gcp_override,json=gcpOverride,proto3" json:"gcp_override,omitempty"`
	AwsOutputs       *NetworkSecurityGroupAwsOutputs    `protobuf:"bytes,6,opt,name=aws_outputs,json=awsOutputs,proto3" json:"aws_outputs,omitempty"`
	AzureOutputs     *NetworkSecurityGroupAzureOutputs  `protobuf:"bytes,7,opt,name=azure_outputs,json=azureOutputs,proto3" json:"azure_outputs,omitempty"`
	GcpOutputs       *NetworkSecurityGroupGcpOutputs    `protobuf:"bytes,8,opt,name=gcp_outputs,json=gcpOutputs,proto3" json:"gcp_outputs,omitempty"`
}

func (x *NetworkSecurityGroupResource) Reset() {
	*x = NetworkSecurityGroupResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSecurityGroupResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSecurityGroupResource) ProtoMessage() {}

func (x *NetworkSecurityGroupResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_network_security_group_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSecurityGroupResource.ProtoReflect.Descriptor instead.
func (*NetworkSecurityGroupResource) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkSecurityGroupResource) GetCommonParameters() *commonpb.CommonResourceParameters {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *NetworkSecurityGroupResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkSecurityGroupResource) GetVirtualNetworkId() string {
	if x != nil {
		return x.VirtualNetworkId
	}
	return ""
}

func (x *NetworkSecurityGroupResource) GetRules() []*NetworkSecurityRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkSecurityGroupResource) GetGcpOverride() *NetworkSecurityGroupGcpOverride {
	if x != nil {
		return x.GcpOverride
	}
	return nil
}

func (x *NetworkSecurityGroupResource) GetAwsOutputs() *NetworkSecurityGroupAwsOutputs {
	if x != nil {
		return x.AwsOutputs
	}
	return nil
}

func (x *NetworkSecurityGroupResource) GetAzureOutputs() *NetworkSecurityGroupAzureOutputs {
	if x != nil {
		return x.AzureOutputs
	}
	return nil
}

func (x *NetworkSecurityGroupResource) GetGcpOutputs() *NetworkSecurityGroupGcpOutputs {
	if x != nil {
		return x.GcpOutputs
	}
	return nil
}

var File_api_proto_resourcespb_network_security_group_proto protoreflect.FileDescriptor

var file_api_proto_resourcespb_network_security_group_proto_rawDesc = []byte{
	0x0a, 0x32, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x21, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x49, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x42, 0x0a, 0x1f, 0x52, 0x65,
	0x61, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x8f,
	0x01, 0x0a, 0x21, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75,
	0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x44, 0x0a, 0x21, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x09, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xe9, 0x01, 0x0a, 0x13, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x69, 0x64, 0x72, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x69, 0x64, 0x72,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x3c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x1f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x47, 0x63, 0x70, 0x4f, 0x76,
	0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0xc8, 0x02, 0x0a, 0x18, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73, 0x12, 0x51, 0x0a,
	0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x52, 0x10,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x64, 0x12, 0x3e, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c,
	0x65, 0x73, 0x12, 0x57, 0x0a, 0x0c, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69,
	0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x47, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x0b,
	0x67, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x4c, 0x0a, 0x1e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x41, 0x77, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x20, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x39, 0x0a,
	0x19, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x16, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x1e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x47, 0x63, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x46, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0xda, 0x04, 0x0a, 0x1c, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x11, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c,
	0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x76, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74,
	0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x57, 0x0a, 0x0c, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x76,
	0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x47, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69,
	0x64, 0x65, 0x52, 0x0b, 0x67, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12,
	0x54, 0x0a, 0x0b, 0x61, 0x77, 0x73, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41,
	0x77, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0a, 0x61, 0x77, 0x73, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x5a, 0x0a, 0x0d, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x52, 0x0c, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x12, 0x54, 0x0a, 0x0b, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c,
	0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x47, 0x63, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0a, 0x67, 0x63, 0x70,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x2a, 0x39, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x0f, 0x42, 0x4f, 0x54, 0x48, 0x5f, 0x44, 0x49, 0x52,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x47,
	0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x47, 0x52, 0x45, 0x53, 0x53,
	0x10, 0x02, 0x42, 0x5e, 0x0a, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x42, 0x0e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6c, 0x74,
	0x79, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_resourcespb_network_security_group_proto_rawDescOnce sync.Once
	file_api_proto_resourcespb_network_security_group_proto_rawDescData = file_api_proto_resourcespb_network_security_group_proto_rawDesc
)

func file_api_proto_resourcespb_network_security_group_proto_rawDescGZIP() []byte {
	file_api_proto_resourcespb_network_security_group_proto_rawDescOnce.Do(func() {
		file_api_proto_resourcespb_network_security_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_resourcespb_network_security_group_proto_rawDescData)
	})
	return file_api_proto_resourcespb_network_security_group_proto_rawDescData
}

var file_api_proto_resourcespb_network_security_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_resourcespb_network_security_group_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_resourcespb_network_security_group_proto_goTypes = []interface{}{
	(Direction)(0), // 0: dev.multy.resources.Direction
	(*CreateNetworkSecurityGroupRequest)(nil), // 1: dev.multy.resources.CreateNetworkSecurityGroupRequest
	(*ReadNetworkSecurityGroupRequest)(nil),   // 2: dev.multy.resources.ReadNetworkSecurityGroupRequest
	(*UpdateNetworkSecurityGroupRequest)(nil), // 3: dev.multy.resources.UpdateNetworkSecurityGroupRequest
	(*DeleteNetworkSecurityGroupRequest)(nil), // 4: dev.multy.resources.DeleteNetworkSecurityGroupRequest
	(*PortRange)(nil),                         // 5: dev.multy.resources.PortRange
	(*NetworkSecurityRule)(nil),               // 6: dev.multy.resources.NetworkSecurityRule
	(*NetworkSecurityGroupGcpOverride)(nil),   // 7: dev.multy.resources.NetworkSecurityGroupGcpOverride
	(*NetworkSecurityGroupArgs)(nil),          // 8: dev.multy.resources.NetworkSecurityGroupArgs
	(*NetworkSecurityGroupAwsOutputs)(nil),    // 9: dev.multy.resources.NetworkSecurityGroupAwsOutputs
	(*NetworkSecurityGroupAzureOutputs)(nil),  // 10: dev.multy.resources.NetworkSecurityGroupAzureOutputs
	(*NetworkSecurityGroupGcpOutputs)(nil),    // 11: dev.multy.resources.NetworkSecurityGroupGcpOutputs
	(*NetworkSecurityGroupResource)(nil),      // 12: dev.multy.resources.NetworkSecurityGroupResource
	(*commonpb.ResourceCommonArgs)(nil),       // 13: dev.multy.common.ResourceCommonArgs
	(*commonpb.CommonResourceParameters)(nil), // 14: dev.multy.common.CommonResourceParameters
}
var file_api_proto_resourcespb_network_security_group_proto_depIdxs = []int32{
	8,  // 0: dev.multy.resources.CreateNetworkSecurityGroupRequest.resource:type_name -> dev.multy.resources.NetworkSecurityGroupArgs
	8,  // 1: dev.multy.resources.UpdateNetworkSecurityGroupRequest.resource:type_name -> dev.multy.resources.NetworkSecurityGroupArgs
	5,  // 2: dev.multy.resources.NetworkSecurityRule.port_range:type_name -> dev.multy.resources.PortRange
	0,  // 3: dev.multy.resources.NetworkSecurityRule.direction:type_name -> dev.multy.resources.Direction
	13, // 4: dev.multy.resources.NetworkSecurityGroupArgs.common_parameters:type_name -> dev.multy.common.ResourceCommonArgs
	6,  // 5: dev.multy.resources.NetworkSecurityGroupArgs.rules:type_name -> dev.multy.resources.NetworkSecurityRule
	7,  // 6: dev.multy.resources.NetworkSecurityGroupArgs.gcp_override:type_name -> dev.multy.resources.NetworkSecurityGroupGcpOverride
	14, // 7: dev.multy.resources.NetworkSecurityGroupResource.common_parameters:type_name -> dev.multy.common.CommonResourceParameters
	6,  // 8: dev.multy.resources.NetworkSecurityGroupResource.rules:type_name -> dev.multy.resources.NetworkSecurityRule
	7,  // 9: dev.multy.resources.NetworkSecurityGroupResource.gcp_override:type_name -> dev.multy.resources.NetworkSecurityGroupGcpOverride
	9,  // 10: dev.multy.resources.NetworkSecurityGroupResource.aws_outputs:type_name -> dev.multy.resources.NetworkSecurityGroupAwsOutputs
	10, // 11: dev.multy.resources.NetworkSecurityGroupResource.azure_outputs:type_name -> dev.multy.resources.NetworkSecurityGroupAzureOutputs
	11, // 12: dev.multy.resources.NetworkSecurityGroupResource.gcp_outputs:type_name -> dev.multy.resources.NetworkSecurityGroupGcpOutputs
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_resourcespb_network_security_group_proto_init() }
func file_api_proto_resourcespb_network_security_group_proto_init() {
	if File_api_proto_resourcespb_network_security_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNetworkSecurityGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNetworkSecurityGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNetworkSecurityGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNetworkSecurityGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityGroupGcpOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityGroupArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityGroupAwsOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityGroupAzureOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityGroupGcpOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_network_security_group_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSecurityGroupResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_resourcespb_network_security_group_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_resourcespb_network_security_group_proto_goTypes,
		DependencyIndexes: file_api_proto_resourcespb_network_security_group_proto_depIdxs,
		EnumInfos:         file_api_proto_resourcespb_network_security_group_proto_enumTypes,
		MessageInfos:      file_api_proto_resourcespb_network_security_group_proto_msgTypes,
	}.Build()
	File_api_proto_resourcespb_network_security_group_proto = out.File
	file_api_proto_resourcespb_network_security_group_proto_rawDesc = nil
	file_api_proto_resourcespb_network_security_group_proto_goTypes = nil
	file_api_proto_resourcespb_network_security_group_proto_depIdxs = nil
}
