// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: api/proto/resourcespb/object_storage_object.proto

package resourcespb

import (
	commonpb "github.com/multycloud/multy/api/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectStorageObjectAcl int32

const (
	ObjectStorageObjectAcl_PRIVATE     ObjectStorageObjectAcl = 0
	ObjectStorageObjectAcl_PUBLIC_READ ObjectStorageObjectAcl = 1
)

// enumValues value maps for ObjectStorageObjectAcl.
var (
	ObjectStorageObjectAcl_name = map[int32]string{
		0: "PRIVATE",
		1: "PUBLIC_READ",
	}
	ObjectStorageObjectAcl_value = map[string]int32{
		"PRIVATE":     0,
		"PUBLIC_READ": 1,
	}
)

func (x ObjectStorageObjectAcl) Enum() *ObjectStorageObjectAcl {
	p := new(ObjectStorageObjectAcl)
	*p = x
	return p
}

func (x ObjectStorageObjectAcl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectStorageObjectAcl) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_resourcespb_object_storage_object_proto_enumTypes[0].Descriptor()
}

func (ObjectStorageObjectAcl) Type() protoreflect.EnumType {
	return &file_api_proto_resourcespb_object_storage_object_proto_enumTypes[0]
}

func (x ObjectStorageObjectAcl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectStorageObjectAcl.Descriptor instead.
func (ObjectStorageObjectAcl) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{0}
}

type CreateObjectStorageObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *ObjectStorageObjectArgs `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CreateObjectStorageObjectRequest) Reset() {
	*x = CreateObjectStorageObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjectStorageObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectStorageObjectRequest) ProtoMessage() {}

func (x *CreateObjectStorageObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectStorageObjectRequest.ProtoReflect.Descriptor instead.
func (*CreateObjectStorageObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{0}
}

func (x *CreateObjectStorageObjectRequest) GetResource() *ObjectStorageObjectArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReadObjectStorageObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *ReadObjectStorageObjectRequest) Reset() {
	*x = ReadObjectStorageObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadObjectStorageObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadObjectStorageObjectRequest) ProtoMessage() {}

func (x *ReadObjectStorageObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadObjectStorageObjectRequest.ProtoReflect.Descriptor instead.
func (*ReadObjectStorageObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{1}
}

func (x *ReadObjectStorageObjectRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type UpdateObjectStorageObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string                   `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Resource   *ObjectStorageObjectArgs `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *UpdateObjectStorageObjectRequest) Reset() {
	*x = UpdateObjectStorageObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObjectStorageObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectStorageObjectRequest) ProtoMessage() {}

func (x *UpdateObjectStorageObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectStorageObjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateObjectStorageObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateObjectStorageObjectRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateObjectStorageObjectRequest) GetResource() *ObjectStorageObjectArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteObjectStorageObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *DeleteObjectStorageObjectRequest) Reset() {
	*x = DeleteObjectStorageObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteObjectStorageObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectStorageObjectRequest) ProtoMessage() {}

func (x *DeleteObjectStorageObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectStorageObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectStorageObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteObjectStorageObjectRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ObjectStorageObjectArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.ChildResourceCommonArgs `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acl              ObjectStorageObjectAcl            `protobuf:"varint,3,opt,name=acl,proto3,enum=dev.multy.resources.ObjectStorageObjectAcl" json:"acl,omitempty"`
	ObjectStorageId  string                            `protobuf:"bytes,4,opt,name=object_storage_id,json=objectStorageId,proto3" json:"object_storage_id,omitempty"`
	Content          string                            `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType      string                            `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Source           string                            `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *ObjectStorageObjectArgs) Reset() {
	*x = ObjectStorageObjectArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageObjectArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageObjectArgs) ProtoMessage() {}

func (x *ObjectStorageObjectArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageObjectArgs.ProtoReflect.Descriptor instead.
func (*ObjectStorageObjectArgs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectStorageObjectArgs) GetCommonParameters() *commonpb.ChildResourceCommonArgs {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *ObjectStorageObjectArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectStorageObjectArgs) GetAcl() ObjectStorageObjectAcl {
	if x != nil {
		return x.Acl
	}
	return ObjectStorageObjectAcl_PRIVATE
}

func (x *ObjectStorageObjectArgs) GetObjectStorageId() string {
	if x != nil {
		return x.ObjectStorageId
	}
	return ""
}

func (x *ObjectStorageObjectArgs) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ObjectStorageObjectArgs) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectStorageObjectArgs) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ObjectStorageObjectResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.CommonChildResourceParameters `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acl              ObjectStorageObjectAcl                  `protobuf:"varint,3,opt,name=acl,proto3,enum=dev.multy.resources.ObjectStorageObjectAcl" json:"acl,omitempty"`
	ObjectStorageId  string                                  `protobuf:"bytes,4,opt,name=object_storage_id,json=objectStorageId,proto3" json:"object_storage_id,omitempty"`
	Content          string                                  `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType      string                                  `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Source           string                                  `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *ObjectStorageObjectResource) Reset() {
	*x = ObjectStorageObjectResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageObjectResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageObjectResource) ProtoMessage() {}

func (x *ObjectStorageObjectResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_object_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageObjectResource.ProtoReflect.Descriptor instead.
func (*ObjectStorageObjectResource) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectStorageObjectResource) GetCommonParameters() *commonpb.CommonChildResourceParameters {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *ObjectStorageObjectResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectStorageObjectResource) GetAcl() ObjectStorageObjectAcl {
	if x != nil {
		return x.Acl
	}
	return ObjectStorageObjectAcl_PRIVATE
}

func (x *ObjectStorageObjectResource) GetObjectStorageId() string {
	if x != nil {
		return x.ObjectStorageId
	}
	return ""
}

func (x *ObjectStorageObjectResource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ObjectStorageObjectResource) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectStorageObjectResource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_api_proto_resourcespb_object_storage_object_proto protoreflect.FileDescriptor

var file_api_proto_resourcespb_object_storage_object_proto_rawDesc = []byte{
	0x0a, 0x31, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x20, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x1e, 0x52, 0x65, 0x61, 0x64, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x20, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x48, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x43, 0x0a, 0x20, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22,
	0xc5, 0x02, 0x0a, 0x17, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x56, 0x0a, 0x11, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c,
	0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x72, 0x67,
	0x73, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x03, 0x61, 0x63, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x63,
	0x6c, 0x52, 0x03, 0x61, 0x63, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0xcf, 0x02, 0x0a, 0x1b, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x03, 0x61, 0x63, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c,
	0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x41, 0x63, 0x6c, 0x52, 0x03, 0x61, 0x63, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2a, 0x36, 0x0a, 0x16, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x41, 0x63, 0x6c, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x10,
	0x01, 0x42, 0x5e, 0x0a, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x42, 0x0e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x79,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_resourcespb_object_storage_object_proto_rawDescOnce sync.Once
	file_api_proto_resourcespb_object_storage_object_proto_rawDescData = file_api_proto_resourcespb_object_storage_object_proto_rawDesc
)

func file_api_proto_resourcespb_object_storage_object_proto_rawDescGZIP() []byte {
	file_api_proto_resourcespb_object_storage_object_proto_rawDescOnce.Do(func() {
		file_api_proto_resourcespb_object_storage_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_resourcespb_object_storage_object_proto_rawDescData)
	})
	return file_api_proto_resourcespb_object_storage_object_proto_rawDescData
}

var file_api_proto_resourcespb_object_storage_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_resourcespb_object_storage_object_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_resourcespb_object_storage_object_proto_goTypes = []interface{}{
	(ObjectStorageObjectAcl)(0),                    // 0: dev.multy.resources.ObjectStorageObjectAcl
	(*CreateObjectStorageObjectRequest)(nil),       // 1: dev.multy.resources.CreateObjectStorageObjectRequest
	(*ReadObjectStorageObjectRequest)(nil),         // 2: dev.multy.resources.ReadObjectStorageObjectRequest
	(*UpdateObjectStorageObjectRequest)(nil),       // 3: dev.multy.resources.UpdateObjectStorageObjectRequest
	(*DeleteObjectStorageObjectRequest)(nil),       // 4: dev.multy.resources.DeleteObjectStorageObjectRequest
	(*ObjectStorageObjectArgs)(nil),                // 5: dev.multy.resources.ObjectStorageObjectArgs
	(*ObjectStorageObjectResource)(nil),            // 6: dev.multy.resources.ObjectStorageObjectResource
	(*commonpb.ChildResourceCommonArgs)(nil),       // 7: dev.multy.common.ChildResourceCommonArgs
	(*commonpb.CommonChildResourceParameters)(nil), // 8: dev.multy.common.CommonChildResourceParameters
}
var file_api_proto_resourcespb_object_storage_object_proto_depIdxs = []int32{
	5, // 0: dev.multy.resources.CreateObjectStorageObjectRequest.resource:type_name -> dev.multy.resources.ObjectStorageObjectArgs
	5, // 1: dev.multy.resources.UpdateObjectStorageObjectRequest.resource:type_name -> dev.multy.resources.ObjectStorageObjectArgs
	7, // 2: dev.multy.resources.ObjectStorageObjectArgs.common_parameters:type_name -> dev.multy.common.ChildResourceCommonArgs
	0, // 3: dev.multy.resources.ObjectStorageObjectArgs.acl:type_name -> dev.multy.resources.ObjectStorageObjectAcl
	8, // 4: dev.multy.resources.ObjectStorageObjectResource.common_parameters:type_name -> dev.multy.common.CommonChildResourceParameters
	0, // 5: dev.multy.resources.ObjectStorageObjectResource.acl:type_name -> dev.multy.resources.ObjectStorageObjectAcl
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_resourcespb_object_storage_object_proto_init() }
func file_api_proto_resourcespb_object_storage_object_proto_init() {
	if File_api_proto_resourcespb_object_storage_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_resourcespb_object_storage_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjectStorageObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadObjectStorageObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObjectStorageObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_object_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteObjectStorageObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_object_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageObjectArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_object_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageObjectResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_resourcespb_object_storage_object_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_resourcespb_object_storage_object_proto_goTypes,
		DependencyIndexes: file_api_proto_resourcespb_object_storage_object_proto_depIdxs,
		EnumInfos:         file_api_proto_resourcespb_object_storage_object_proto_enumTypes,
		MessageInfos:      file_api_proto_resourcespb_object_storage_object_proto_msgTypes,
	}.Build()
	File_api_proto_resourcespb_object_storage_object_proto = out.File
	file_api_proto_resourcespb_object_storage_object_proto_rawDesc = nil
	file_api_proto_resourcespb_object_storage_object_proto_goTypes = nil
	file_api_proto_resourcespb_object_storage_object_proto_depIdxs = nil
}
