// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/proto/resourcespb/object_storage.proto

package resourcespb

import (
	commonpb "github.com/multycloud/multy/api/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateObjectStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *ObjectStorageArgs `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CreateObjectStorageRequest) Reset() {
	*x = CreateObjectStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjectStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectStorageRequest) ProtoMessage() {}

func (x *CreateObjectStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectStorageRequest.ProtoReflect.Descriptor instead.
func (*CreateObjectStorageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CreateObjectStorageRequest) GetResource() *ObjectStorageArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReadObjectStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *ReadObjectStorageRequest) Reset() {
	*x = ReadObjectStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadObjectStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadObjectStorageRequest) ProtoMessage() {}

func (x *ReadObjectStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadObjectStorageRequest.ProtoReflect.Descriptor instead.
func (*ReadObjectStorageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ReadObjectStorageRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type UpdateObjectStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string             `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Resource   *ObjectStorageArgs `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *UpdateObjectStorageRequest) Reset() {
	*x = UpdateObjectStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObjectStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectStorageRequest) ProtoMessage() {}

func (x *UpdateObjectStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectStorageRequest.ProtoReflect.Descriptor instead.
func (*UpdateObjectStorageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateObjectStorageRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateObjectStorageRequest) GetResource() *ObjectStorageArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteObjectStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *DeleteObjectStorageRequest) Reset() {
	*x = DeleteObjectStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteObjectStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectStorageRequest) ProtoMessage() {}

func (x *DeleteObjectStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectStorageRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectStorageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteObjectStorageRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ObjectStorageGcpOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *ObjectStorageGcpOverride) Reset() {
	*x = ObjectStorageGcpOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageGcpOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageGcpOverride) ProtoMessage() {}

func (x *ObjectStorageGcpOverride) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageGcpOverride.ProtoReflect.Descriptor instead.
func (*ObjectStorageGcpOverride) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectStorageGcpOverride) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type ObjectStorageArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.ResourceCommonArgs `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Versioning       bool                         `protobuf:"varint,3,opt,name=versioning,proto3" json:"versioning,omitempty"`
	GcpOverride      *ObjectStorageGcpOverride    `protobuf:"bytes,4,opt,name=gcp_override,json=gcpOverride,proto3" json:"gcp_override,omitempty"`
}

func (x *ObjectStorageArgs) Reset() {
	*x = ObjectStorageArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageArgs) ProtoMessage() {}

func (x *ObjectStorageArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageArgs.ProtoReflect.Descriptor instead.
func (*ObjectStorageArgs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectStorageArgs) GetCommonParameters() *commonpb.ResourceCommonArgs {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *ObjectStorageArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectStorageArgs) GetVersioning() bool {
	if x != nil {
		return x.Versioning
	}
	return false
}

func (x *ObjectStorageArgs) GetGcpOverride() *ObjectStorageGcpOverride {
	if x != nil {
		return x.GcpOverride
	}
	return nil
}

type ObjectStorageAwsOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S3BucketArn string `protobuf:"bytes,1,opt,name=s3_bucket_arn,json=s3BucketArn,proto3" json:"s3_bucket_arn,omitempty"`
}

func (x *ObjectStorageAwsOutputs) Reset() {
	*x = ObjectStorageAwsOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageAwsOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageAwsOutputs) ProtoMessage() {}

func (x *ObjectStorageAwsOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageAwsOutputs.ProtoReflect.Descriptor instead.
func (*ObjectStorageAwsOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectStorageAwsOutputs) GetS3BucketArn() string {
	if x != nil {
		return x.S3BucketArn
	}
	return ""
}

type ObjectStorageAzureOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageAccountId          string `protobuf:"bytes,1,opt,name=storage_account_id,json=storageAccountId,proto3" json:"storage_account_id,omitempty"`
	PublicStorageContainerId  string `protobuf:"bytes,2,opt,name=public_storage_container_id,json=publicStorageContainerId,proto3" json:"public_storage_container_id,omitempty"`
	PrivateStorageContainerId string `protobuf:"bytes,3,opt,name=private_storage_container_id,json=privateStorageContainerId,proto3" json:"private_storage_container_id,omitempty"`
}

func (x *ObjectStorageAzureOutputs) Reset() {
	*x = ObjectStorageAzureOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageAzureOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageAzureOutputs) ProtoMessage() {}

func (x *ObjectStorageAzureOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageAzureOutputs.ProtoReflect.Descriptor instead.
func (*ObjectStorageAzureOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectStorageAzureOutputs) GetStorageAccountId() string {
	if x != nil {
		return x.StorageAccountId
	}
	return ""
}

func (x *ObjectStorageAzureOutputs) GetPublicStorageContainerId() string {
	if x != nil {
		return x.PublicStorageContainerId
	}
	return ""
}

func (x *ObjectStorageAzureOutputs) GetPrivateStorageContainerId() string {
	if x != nil {
		return x.PrivateStorageContainerId
	}
	return ""
}

type ObjectStorageGcpOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageBucketId string `protobuf:"bytes,1,opt,name=storage_bucket_id,json=storageBucketId,proto3" json:"storage_bucket_id,omitempty"`
}

func (x *ObjectStorageGcpOutputs) Reset() {
	*x = ObjectStorageGcpOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageGcpOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageGcpOutputs) ProtoMessage() {}

func (x *ObjectStorageGcpOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageGcpOutputs.ProtoReflect.Descriptor instead.
func (*ObjectStorageGcpOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectStorageGcpOutputs) GetStorageBucketId() string {
	if x != nil {
		return x.StorageBucketId
	}
	return ""
}

type ObjectStorageResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.CommonResourceParameters `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Versioning       bool                               `protobuf:"varint,3,opt,name=versioning,proto3" json:"versioning,omitempty"`
	GcpOverride      *ObjectStorageGcpOverride          `protobuf:"bytes,4,opt,name=gcp_override,json=gcpOverride,proto3" json:"gcp_override,omitempty"`
	AwsOutputs       *ObjectStorageAwsOutputs           `protobuf:"bytes,5,opt,name=aws_outputs,json=awsOutputs,proto3" json:"aws_outputs,omitempty"`
	AzureOutputs     *ObjectStorageAzureOutputs         `protobuf:"bytes,6,opt,name=azure_outputs,json=azureOutputs,proto3" json:"azure_outputs,omitempty"`
	GcpOutputs       *ObjectStorageGcpOutputs           `protobuf:"bytes,7,opt,name=gcp_outputs,json=gcpOutputs,proto3" json:"gcp_outputs,omitempty"`
}

func (x *ObjectStorageResource) Reset() {
	*x = ObjectStorageResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectStorageResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageResource) ProtoMessage() {}

func (x *ObjectStorageResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_object_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageResource.ProtoReflect.Descriptor instead.
func (*ObjectStorageResource) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_object_storage_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectStorageResource) GetCommonParameters() *commonpb.CommonResourceParameters {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *ObjectStorageResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectStorageResource) GetVersioning() bool {
	if x != nil {
		return x.Versioning
	}
	return false
}

func (x *ObjectStorageResource) GetGcpOverride() *ObjectStorageGcpOverride {
	if x != nil {
		return x.GcpOverride
	}
	return nil
}

func (x *ObjectStorageResource) GetAwsOutputs() *ObjectStorageAwsOutputs {
	if x != nil {
		return x.AwsOutputs
	}
	return nil
}

func (x *ObjectStorageResource) GetAzureOutputs() *ObjectStorageAzureOutputs {
	if x != nil {
		return x.AzureOutputs
	}
	return nil
}

func (x *ObjectStorageResource) GetGcpOutputs() *ObjectStorageGcpOutputs {
	if x != nil {
		return x.GcpOutputs
	}
	return nil
}

var File_api_proto_resourcespb_object_storage_proto protoreflect.FileDescriptor

var file_api_proto_resourcespb_object_storage_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x65,
	0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x60, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x42, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x81, 0x01, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x42, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x3d, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x47, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x22, 0xec, 0x01, 0x0a, 0x11, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x51, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x72, 0x67,
	0x73, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x50, 0x0a, 0x0c, 0x67, 0x63, 0x70, 0x5f, 0x6f,
	0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x47, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x0b, 0x67, 0x63,
	0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x17, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x77, 0x73, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x33, 0x5f, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x33, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x72, 0x6e, 0x22, 0xc9, 0x01, 0x0a, 0x19, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x1b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x1c, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x47, 0x63, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12,
	0x2a, 0x0a, 0x11, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0xe9, 0x03, 0x0a, 0x15,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x10, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x50, 0x0a, 0x0c, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x47, 0x63, 0x70, 0x4f,
	0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x0b, 0x67, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x12, 0x4d, 0x0a, 0x0b, 0x61, 0x77, 0x73, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x77, 0x73,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0a, 0x61, 0x77, 0x73, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x12, 0x53, 0x0a, 0x0d, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x5f, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x7a,
	0x75, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0c, 0x61, 0x7a, 0x75, 0x72,
	0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x4d, 0x0a, 0x0b, 0x67, 0x63, 0x70, 0x5f,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x47, 0x63, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0a, 0x67, 0x63, 0x70,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x42, 0x5e, 0x0a, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x42, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6d, 0x75, 0x6c, 0x74,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_resourcespb_object_storage_proto_rawDescOnce sync.Once
	file_api_proto_resourcespb_object_storage_proto_rawDescData = file_api_proto_resourcespb_object_storage_proto_rawDesc
)

func file_api_proto_resourcespb_object_storage_proto_rawDescGZIP() []byte {
	file_api_proto_resourcespb_object_storage_proto_rawDescOnce.Do(func() {
		file_api_proto_resourcespb_object_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_resourcespb_object_storage_proto_rawDescData)
	})
	return file_api_proto_resourcespb_object_storage_proto_rawDescData
}

var file_api_proto_resourcespb_object_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_resourcespb_object_storage_proto_goTypes = []interface{}{
	(*CreateObjectStorageRequest)(nil),        // 0: dev.multy.resources.CreateObjectStorageRequest
	(*ReadObjectStorageRequest)(nil),          // 1: dev.multy.resources.ReadObjectStorageRequest
	(*UpdateObjectStorageRequest)(nil),        // 2: dev.multy.resources.UpdateObjectStorageRequest
	(*DeleteObjectStorageRequest)(nil),        // 3: dev.multy.resources.DeleteObjectStorageRequest
	(*ObjectStorageGcpOverride)(nil),          // 4: dev.multy.resources.ObjectStorageGcpOverride
	(*ObjectStorageArgs)(nil),                 // 5: dev.multy.resources.ObjectStorageArgs
	(*ObjectStorageAwsOutputs)(nil),           // 6: dev.multy.resources.ObjectStorageAwsOutputs
	(*ObjectStorageAzureOutputs)(nil),         // 7: dev.multy.resources.ObjectStorageAzureOutputs
	(*ObjectStorageGcpOutputs)(nil),           // 8: dev.multy.resources.ObjectStorageGcpOutputs
	(*ObjectStorageResource)(nil),             // 9: dev.multy.resources.ObjectStorageResource
	(*commonpb.ResourceCommonArgs)(nil),       // 10: dev.multy.common.ResourceCommonArgs
	(*commonpb.CommonResourceParameters)(nil), // 11: dev.multy.common.CommonResourceParameters
}
var file_api_proto_resourcespb_object_storage_proto_depIdxs = []int32{
	5,  // 0: dev.multy.resources.CreateObjectStorageRequest.resource:type_name -> dev.multy.resources.ObjectStorageArgs
	5,  // 1: dev.multy.resources.UpdateObjectStorageRequest.resource:type_name -> dev.multy.resources.ObjectStorageArgs
	10, // 2: dev.multy.resources.ObjectStorageArgs.common_parameters:type_name -> dev.multy.common.ResourceCommonArgs
	4,  // 3: dev.multy.resources.ObjectStorageArgs.gcp_override:type_name -> dev.multy.resources.ObjectStorageGcpOverride
	11, // 4: dev.multy.resources.ObjectStorageResource.common_parameters:type_name -> dev.multy.common.CommonResourceParameters
	4,  // 5: dev.multy.resources.ObjectStorageResource.gcp_override:type_name -> dev.multy.resources.ObjectStorageGcpOverride
	6,  // 6: dev.multy.resources.ObjectStorageResource.aws_outputs:type_name -> dev.multy.resources.ObjectStorageAwsOutputs
	7,  // 7: dev.multy.resources.ObjectStorageResource.azure_outputs:type_name -> dev.multy.resources.ObjectStorageAzureOutputs
	8,  // 8: dev.multy.resources.ObjectStorageResource.gcp_outputs:type_name -> dev.multy.resources.ObjectStorageGcpOutputs
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_resourcespb_object_storage_proto_init() }
func file_api_proto_resourcespb_object_storage_proto_init() {
	if File_api_proto_resourcespb_object_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_resourcespb_object_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjectStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadObjectStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObjectStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteObjectStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageGcpOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageAwsOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageAzureOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageGcpOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_object_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectStorageResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_resourcespb_object_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_resourcespb_object_storage_proto_goTypes,
		DependencyIndexes: file_api_proto_resourcespb_object_storage_proto_depIdxs,
		MessageInfos:      file_api_proto_resourcespb_object_storage_proto_msgTypes,
	}.Build()
	File_api_proto_resourcespb_object_storage_proto = out.File
	file_api_proto_resourcespb_object_storage_proto_rawDesc = nil
	file_api_proto_resourcespb_object_storage_proto_goTypes = nil
	file_api_proto_resourcespb_object_storage_proto_depIdxs = nil
}
