// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/proto/resourcespb/vault_secret.proto

package resourcespb

import (
	commonpb "github.com/multycloud/multy/api/proto/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVaultSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *VaultSecretArgs `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CreateVaultSecretRequest) Reset() {
	*x = CreateVaultSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVaultSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVaultSecretRequest) ProtoMessage() {}

func (x *CreateVaultSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVaultSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateVaultSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVaultSecretRequest) GetResource() *VaultSecretArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReadVaultSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *ReadVaultSecretRequest) Reset() {
	*x = ReadVaultSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadVaultSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVaultSecretRequest) ProtoMessage() {}

func (x *ReadVaultSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVaultSecretRequest.ProtoReflect.Descriptor instead.
func (*ReadVaultSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{1}
}

func (x *ReadVaultSecretRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type UpdateVaultSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string           `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Resource   *VaultSecretArgs `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *UpdateVaultSecretRequest) Reset() {
	*x = UpdateVaultSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVaultSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultSecretRequest) ProtoMessage() {}

func (x *UpdateVaultSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVaultSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateVaultSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateVaultSecretRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateVaultSecretRequest) GetResource() *VaultSecretArgs {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteVaultSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *DeleteVaultSecretRequest) Reset() {
	*x = DeleteVaultSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVaultSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVaultSecretRequest) ProtoMessage() {}

func (x *DeleteVaultSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVaultSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteVaultSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVaultSecretRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type VaultSecretGcpOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlobalReplication bool `protobuf:"varint,1,opt,name=global_replication,json=globalReplication,proto3" json:"global_replication,omitempty"`
}

func (x *VaultSecretGcpOverride) Reset() {
	*x = VaultSecretGcpOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecretGcpOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecretGcpOverride) ProtoMessage() {}

func (x *VaultSecretGcpOverride) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecretGcpOverride.ProtoReflect.Descriptor instead.
func (*VaultSecretGcpOverride) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{4}
}

func (x *VaultSecretGcpOverride) GetGlobalReplication() bool {
	if x != nil {
		return x.GlobalReplication
	}
	return false
}

type VaultSecretArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.ChildResourceCommonArgs `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value            string                            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	VaultId          string                            `protobuf:"bytes,4,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	GcpOverride      *VaultSecretGcpOverride           `protobuf:"bytes,5,opt,name=gcp_override,json=gcpOverride,proto3" json:"gcp_override,omitempty"`
}

func (x *VaultSecretArgs) Reset() {
	*x = VaultSecretArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecretArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecretArgs) ProtoMessage() {}

func (x *VaultSecretArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecretArgs.ProtoReflect.Descriptor instead.
func (*VaultSecretArgs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{5}
}

func (x *VaultSecretArgs) GetCommonParameters() *commonpb.ChildResourceCommonArgs {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *VaultSecretArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultSecretArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VaultSecretArgs) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultSecretArgs) GetGcpOverride() *VaultSecretGcpOverride {
	if x != nil {
		return x.GcpOverride
	}
	return nil
}

type VaultSecretAwsOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SsmParameterArn string `protobuf:"bytes,1,opt,name=ssm_parameter_arn,json=ssmParameterArn,proto3" json:"ssm_parameter_arn,omitempty"`
}

func (x *VaultSecretAwsOutputs) Reset() {
	*x = VaultSecretAwsOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecretAwsOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecretAwsOutputs) ProtoMessage() {}

func (x *VaultSecretAwsOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecretAwsOutputs.ProtoReflect.Descriptor instead.
func (*VaultSecretAwsOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{6}
}

func (x *VaultSecretAwsOutputs) GetSsmParameterArn() string {
	if x != nil {
		return x.SsmParameterArn
	}
	return ""
}

type VaultSecretAzureOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyVaultSecretId string `protobuf:"bytes,1,opt,name=key_vault_secret_id,json=keyVaultSecretId,proto3" json:"key_vault_secret_id,omitempty"`
}

func (x *VaultSecretAzureOutputs) Reset() {
	*x = VaultSecretAzureOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecretAzureOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecretAzureOutputs) ProtoMessage() {}

func (x *VaultSecretAzureOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecretAzureOutputs.ProtoReflect.Descriptor instead.
func (*VaultSecretAzureOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{7}
}

func (x *VaultSecretAzureOutputs) GetKeyVaultSecretId() string {
	if x != nil {
		return x.KeyVaultSecretId
	}
	return ""
}

type VaultSecretGcpOutputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretManagerSecretId        string `protobuf:"bytes,1,opt,name=secret_manager_secret_id,json=secretManagerSecretId,proto3" json:"secret_manager_secret_id,omitempty"`
	SecretManagerSecretVersionId string `protobuf:"bytes,2,opt,name=secret_manager_secret_version_id,json=secretManagerSecretVersionId,proto3" json:"secret_manager_secret_version_id,omitempty"`
}

func (x *VaultSecretGcpOutputs) Reset() {
	*x = VaultSecretGcpOutputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecretGcpOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecretGcpOutputs) ProtoMessage() {}

func (x *VaultSecretGcpOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecretGcpOutputs.ProtoReflect.Descriptor instead.
func (*VaultSecretGcpOutputs) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{8}
}

func (x *VaultSecretGcpOutputs) GetSecretManagerSecretId() string {
	if x != nil {
		return x.SecretManagerSecretId
	}
	return ""
}

func (x *VaultSecretGcpOutputs) GetSecretManagerSecretVersionId() string {
	if x != nil {
		return x.SecretManagerSecretVersionId
	}
	return ""
}

type VaultSecretResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonParameters *commonpb.CommonChildResourceParameters `protobuf:"bytes,1,opt,name=common_parameters,json=commonParameters,proto3" json:"common_parameters,omitempty"`
	Name             string                                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value            string                                  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	VaultId          string                                  `protobuf:"bytes,4,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	GcpOverride      *VaultSecretGcpOverride                 `protobuf:"bytes,5,opt,name=gcp_override,json=gcpOverride,proto3" json:"gcp_override,omitempty"`
	AwsOutputs       *VaultSecretAwsOutputs                  `protobuf:"bytes,6,opt,name=aws_outputs,json=awsOutputs,proto3" json:"aws_outputs,omitempty"`
	AzureOutputs     *VaultSecretAzureOutputs                `protobuf:"bytes,7,opt,name=azure_outputs,json=azureOutputs,proto3" json:"azure_outputs,omitempty"`
	GcpOutputs       *VaultSecretGcpOutputs                  `protobuf:"bytes,8,opt,name=gcp_outputs,json=gcpOutputs,proto3" json:"gcp_outputs,omitempty"`
}

func (x *VaultSecretResource) Reset() {
	*x = VaultSecretResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaultSecretResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultSecretResource) ProtoMessage() {}

func (x *VaultSecretResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_resourcespb_vault_secret_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultSecretResource.ProtoReflect.Descriptor instead.
func (*VaultSecretResource) Descriptor() ([]byte, []int) {
	return file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP(), []int{9}
}

func (x *VaultSecretResource) GetCommonParameters() *commonpb.CommonChildResourceParameters {
	if x != nil {
		return x.CommonParameters
	}
	return nil
}

func (x *VaultSecretResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultSecretResource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VaultSecretResource) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultSecretResource) GetGcpOverride() *VaultSecretGcpOverride {
	if x != nil {
		return x.GcpOverride
	}
	return nil
}

func (x *VaultSecretResource) GetAwsOutputs() *VaultSecretAwsOutputs {
	if x != nil {
		return x.AwsOutputs
	}
	return nil
}

func (x *VaultSecretResource) GetAzureOutputs() *VaultSecretAzureOutputs {
	if x != nil {
		return x.AzureOutputs
	}
	return nil
}

func (x *VaultSecretResource) GetGcpOutputs() *VaultSecretGcpOutputs {
	if x != nil {
		return x.GcpOutputs
	}
	return nil
}

var File_api_proto_resourcespb_vault_secret_proto protoreflect.FileDescriptor

var file_api_proto_resourcespb_vault_secret_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x65, 0x76, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a,
	0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5c, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x39,
	0x0a, 0x16, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x18, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x3b, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x16, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x47, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12,
	0x2d, 0x0a, 0x12, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xfe,
	0x01, 0x0a, 0x0f, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x56, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x12,
	0x4e, 0x0a, 0x0c, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74,
	0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x47, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69,
	0x64, 0x65, 0x52, 0x0b, 0x67, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22,
	0x43, 0x0a, 0x15, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x77,
	0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x73, 0x6d, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x72, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x73, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x41, 0x72, 0x6e, 0x22, 0x48, 0x0a, 0x17, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12,
	0x2d, 0x0a, 0x13, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6b, 0x65,
	0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x22, 0x98,
	0x01, 0x0a, 0x15, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x47, 0x63,
	0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x18, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x46, 0x0a, 0x20, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1c, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xf5, 0x03, 0x0a, 0x13, 0x56, 0x61,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x5c, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x10, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x49, 0x64, 0x12, 0x4e, 0x0a, 0x0c, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x47, 0x63, 0x70, 0x4f,
	0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x52, 0x0b, 0x67, 0x63, 0x70, 0x4f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x12, 0x4b, 0x0a, 0x0b, 0x61, 0x77, 0x73, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x77, 0x73, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0a, 0x61, 0x77, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x12, 0x51, 0x0a, 0x0d, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0c, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x4b, 0x0a, 0x0b, 0x67, 0x63, 0x70, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x47, 0x63, 0x70, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x52, 0x0a, 0x67, 0x63, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x42, 0x5e, 0x0a, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x42, 0x0e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x79,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_resourcespb_vault_secret_proto_rawDescOnce sync.Once
	file_api_proto_resourcespb_vault_secret_proto_rawDescData = file_api_proto_resourcespb_vault_secret_proto_rawDesc
)

func file_api_proto_resourcespb_vault_secret_proto_rawDescGZIP() []byte {
	file_api_proto_resourcespb_vault_secret_proto_rawDescOnce.Do(func() {
		file_api_proto_resourcespb_vault_secret_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_resourcespb_vault_secret_proto_rawDescData)
	})
	return file_api_proto_resourcespb_vault_secret_proto_rawDescData
}

var file_api_proto_resourcespb_vault_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_resourcespb_vault_secret_proto_goTypes = []interface{}{
	(*CreateVaultSecretRequest)(nil),               // 0: dev.multy.resources.CreateVaultSecretRequest
	(*ReadVaultSecretRequest)(nil),                 // 1: dev.multy.resources.ReadVaultSecretRequest
	(*UpdateVaultSecretRequest)(nil),               // 2: dev.multy.resources.UpdateVaultSecretRequest
	(*DeleteVaultSecretRequest)(nil),               // 3: dev.multy.resources.DeleteVaultSecretRequest
	(*VaultSecretGcpOverride)(nil),                 // 4: dev.multy.resources.VaultSecretGcpOverride
	(*VaultSecretArgs)(nil),                        // 5: dev.multy.resources.VaultSecretArgs
	(*VaultSecretAwsOutputs)(nil),                  // 6: dev.multy.resources.VaultSecretAwsOutputs
	(*VaultSecretAzureOutputs)(nil),                // 7: dev.multy.resources.VaultSecretAzureOutputs
	(*VaultSecretGcpOutputs)(nil),                  // 8: dev.multy.resources.VaultSecretGcpOutputs
	(*VaultSecretResource)(nil),                    // 9: dev.multy.resources.VaultSecretResource
	(*commonpb.ChildResourceCommonArgs)(nil),       // 10: dev.multy.common.ChildResourceCommonArgs
	(*commonpb.CommonChildResourceParameters)(nil), // 11: dev.multy.common.CommonChildResourceParameters
}
var file_api_proto_resourcespb_vault_secret_proto_depIdxs = []int32{
	5,  // 0: dev.multy.resources.CreateVaultSecretRequest.resource:type_name -> dev.multy.resources.VaultSecretArgs
	5,  // 1: dev.multy.resources.UpdateVaultSecretRequest.resource:type_name -> dev.multy.resources.VaultSecretArgs
	10, // 2: dev.multy.resources.VaultSecretArgs.common_parameters:type_name -> dev.multy.common.ChildResourceCommonArgs
	4,  // 3: dev.multy.resources.VaultSecretArgs.gcp_override:type_name -> dev.multy.resources.VaultSecretGcpOverride
	11, // 4: dev.multy.resources.VaultSecretResource.common_parameters:type_name -> dev.multy.common.CommonChildResourceParameters
	4,  // 5: dev.multy.resources.VaultSecretResource.gcp_override:type_name -> dev.multy.resources.VaultSecretGcpOverride
	6,  // 6: dev.multy.resources.VaultSecretResource.aws_outputs:type_name -> dev.multy.resources.VaultSecretAwsOutputs
	7,  // 7: dev.multy.resources.VaultSecretResource.azure_outputs:type_name -> dev.multy.resources.VaultSecretAzureOutputs
	8,  // 8: dev.multy.resources.VaultSecretResource.gcp_outputs:type_name -> dev.multy.resources.VaultSecretGcpOutputs
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_resourcespb_vault_secret_proto_init() }
func file_api_proto_resourcespb_vault_secret_proto_init() {
	if File_api_proto_resourcespb_vault_secret_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVaultSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadVaultSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVaultSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVaultSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecretGcpOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecretArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecretAwsOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecretAzureOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecretGcpOutputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_resourcespb_vault_secret_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaultSecretResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_resourcespb_vault_secret_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_resourcespb_vault_secret_proto_goTypes,
		DependencyIndexes: file_api_proto_resourcespb_vault_secret_proto_depIdxs,
		MessageInfos:      file_api_proto_resourcespb_vault_secret_proto_msgTypes,
	}.Build()
	File_api_proto_resourcespb_vault_secret_proto = out.File
	file_api_proto_resourcespb_vault_secret_proto_rawDesc = nil
	file_api_proto_resourcespb_vault_secret_proto_goTypes = nil
	file_api_proto_resourcespb_vault_secret_proto_depIdxs = nil
}
