resources:  {
  resource_id:  "example_azure"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VaultArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  AZURE
        }
        name:  "dev-test-multy"
      }
    }
  }
}
resources:  {
  resource_id:  "example_aws"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VaultArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  AWS
        }
        name:  "dev-test-multy"
      }
    }
  }
}
resources:  {
  resource_id:  "example_gcp"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.VaultArgs]:  {
        common_parameters:  {
          resource_group_id:  "rg1"
          location:  EU_WEST_1
          cloud_provider:  GCP
        }
        name:  "dev-test-multy"
      }
    }
  }
}
resources:  {
  resource_id:  "rg1"
  resource_args:  {
    resource_args:  {
      [type.googleapis.com/dev.multy.resources.ResourceGroupArgs]:  {
        common_parameters:  {
          location:  EU_WEST_1
          cloud_provider:  AZURE
        }
        name:  "rg1"
      }
    }
  }
}


# proto-file: api/proto/configpb/config.proto
# proto-import: api/proto/resourcespb/database.proto
# proto-import: api/proto/resourcespb/kubernetes_cluster.proto
# proto-import: api/proto/resourcespb/kubernetes_node_pool.proto
# proto-import: api/proto/resourcespb/lambda.proto
# proto-import: api/proto/resourcespb/network_interface.proto
# proto-import: api/proto/resourcespb/network_security_group.proto
# proto-import: api/proto/resourcespb/public_ip.proto
# proto-import: api/proto/resourcespb/resource_group.proto
# proto-import: api/proto/resourcespb/route_table_association.proto
# proto-import: api/proto/resourcespb/object_storage.proto
# proto-import: api/proto/resourcespb/object_storage_object.proto
# proto-import: api/proto/resourcespb/route_table.proto
# proto-import: api/proto/resourcespb/subnet.proto
# proto-import: api/proto/resourcespb/vault.proto
# proto-import: api/proto/resourcespb/vault_access_policy.proto
# proto-import: api/proto/resourcespb/vault_secret.proto
# proto-import: api/proto/resourcespb/virtual_machine.proto
# proto-import: api/proto/resourcespb/virtual_network.proto
# proto-message: config.Config
