name: "e2e"
on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.*'
          terraform_wrapper: false

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Set up protoc
        uses: arduino/setup-protoc@v1

      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint@latest

      - name: Mod tidy
        run: go mod tidy

      - name: Build
        run: make build

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Test
        run: go test ./test/e2e -tags=e2e -timeout=180m -parallel 4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_E2E }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_E2E }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_E2E }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_E2E }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_E2E }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
