name: go_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Go 1.18beta1
        run: |
          go install golang.org/dl/go1.18beta1@latest
          go1.18beta1 download

      - name: Install dependencies
        run: |
          go1.18beta1 version
          go1.18beta1 install golang.org/x/lint/golint@latest


      - name: Mod tidy
        run: go1.18beta1 mod tidy

      - name: Build
        run: go1.18beta1 build -v ./...

      - name: Run vet & lint
        run: |
          go1.18beta1 vet .
          golint .

      - name: Test
        run: go1.18beta1 test -v -plan .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}